version: "3.9"
services:
  cdxgen:
    image: ghcr.io/appthreat/cdxgen
    ports:
      - "9090:9090"
    volumes:
      - /tmp:/tmp
      - $PWD:/app
    command: cdxgen --server --server-host 0.0.0.0 --server-port 9090

  depscan:
    image: ghcr.io/appthreat/dep-scan
    ports:
      - "7070:7070"
    volumes:
      - /tmp:/tmp
      - $PWD:/app
    entrypoint: depscan --server --server-host 0.0.0.0 --server-port 7070 --cdxgen-server http://cdxgen:9090
    environment:
      VDB_HOME: /tmp/vdb

  cpggen:
    image: ghcr.io/appthreat/cpggen-oss:main
    ports:
      - "7072:7072"
    volumes:
      - /tmp:/tmp
      - $PWD:/app
    command: cpggen --server --server-host 0.0.0.0 --server-port 7072

  joern:
    image: ghcr.io/appthreat/cpggen-oss:main
    ports:
      - "9000:9000"
    volumes:
      - /tmp:/tmp
      - $PWD:/app
    command: joern --server --server-host 0.0.0.0 --server-port 9000 --server-auth-username admin --server-auth-password admin

  polynote:
    image: ghcr.io/appthreat/polynote
    volumes:
      - ./contrib/polynote/notebooks:/opt/notebooks
      - ./contrib/polynote/config.yml:/opt/config/config.yml
      - /tmp:/tmp
      - ./:/opt/joern_lib
    ports:
      - "8192:8192"
    command: --config /opt/config/config.yml
